generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Song
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          song
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [ title ]


      filter:  ~
      form:    ~
      edit:
        display: [ title, lyrics, artists_list ]
      new:     ~
