<?php

/**
 * BaseArtistSong
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $artist_id
 * @property integer $song_id
 * @property Artist $artist
 * @property Song $song
 * 
 * @method integer    getArtistId()  Returns the current record's "artist_id" value
 * @method integer    getSongId()    Returns the current record's "song_id" value
 * @method Artist     getArtist()    Returns the current record's "artist" value
 * @method Song       getSong()      Returns the current record's "song" value
 * @method ArtistSong setArtistId()  Sets the current record's "artist_id" value
 * @method ArtistSong setSongId()    Sets the current record's "song_id" value
 * @method ArtistSong setArtist()    Sets the current record's "artist" value
 * @method ArtistSong setSong()      Sets the current record's "song" value
 * 
 * @package    Blues
 * @subpackage model
 * @author     Włodzimierz Gajda
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtistSong extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artist_has_song');
        $this->hasColumn('artist_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('song_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));


        $this->index('fk_artist_has_song_artist', array(
             'fields' => 
             array(
              0 => 'artist_id',
             ),
             ));
        $this->index('fk_artist_has_song_song', array(
             'fields' => 
             array(
              0 => 'song_id',
             ),
             ));
        $this->option('collate', 'utf8_polish_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Artist as artist', array(
             'local' => 'artist_id',
             'foreign' => 'id'));

        $this->hasOne('Song as song', array(
             'local' => 'song_id',
             'foreign' => 'id'));
    }
}