<?php

/**
 * BaseSong
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $lyrics
 * @property Doctrine_Collection $artists
 * @property Doctrine_Collection $clips
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getTitle()   Returns the current record's "title" value
 * @method string              getLyrics()  Returns the current record's "lyrics" value
 * @method Doctrine_Collection getArtists() Returns the current record's "artists" collection
 * @method Doctrine_Collection getClips()   Returns the current record's "clips" collection
 * @method Song                setId()      Sets the current record's "id" value
 * @method Song                setTitle()   Sets the current record's "title" value
 * @method Song                setLyrics()  Sets the current record's "lyrics" value
 * @method Song                setArtists() Sets the current record's "artists" collection
 * @method Song                setClips()   Sets the current record's "clips" collection
 * 
 * @package    Blues
 * @subpackage model
 * @author     Włodzimierz Gajda
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSong extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('song');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('lyrics', 'string', 4096, array(
             'type' => 'string',
             'length' => 4096,
             ));

        $this->option('orderBy', 'title');
        $this->option('collate', 'utf8_polish_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Artist as artists', array(
             'refClass' => 'ArtistSong',
             'local' => 'song_id',
             'foreign' => 'artist_id'));

        $this->hasMany('Clip as clips', array(
             'local' => 'id',
             'foreign' => 'song_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => false,
             ));
        $this->actAs($sluggable0);
    }
}