<?php

/**
 * ArtistSongTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArtistSongTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object ArtistSongTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('ArtistSong');
  }

}