<?php

/**
 * Artist
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Blues
 * @subpackage model
 * @author     Włodzimierz Gajda
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Artist extends BaseArtist
{

}