<?php

/**
 * SongTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SongTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object SongTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Song');
  }

}