<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('artist', 'surname', 'string', '128', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('artist', 'surname');
    }
}