<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('clip', 'ble');
        $this->changeColumn('clip', 'width', 'integer', '8', array(
             'default' => '420',
             ));
        $this->changeColumn('clip', 'height', 'integer', '8', array(
             'default' => '315',
             ));
    }

    public function down()
    {
        $this->addColumn('clip', 'ble', 'integer', '8', array(
             'default' => '7890',
             ));
    }
}