<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('clip', 'fk_clip_song', array(
             'fields' => 
             array(
              0 => 'song_id',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('clip', 'fk_clip_song', array(
             'fields' => 
             array(
              0 => 'song_id',
             ),
             ));
    }
}