<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsong extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('song', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('song');
    }
}