<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('clip', 'html', 'string', '4096', array(
             ));
    }

    public function down()
    {

    }
}