<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('artist', 'ble', 'string', '128', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('artist', 'ble');
    }
}