<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version25 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tasks', 'tasks_priority_id_priority_id', array(
             'name' => 'tasks_priority_id_priority_id',
             'local' => 'priority_id',
             'foreign' => 'id',
             'foreignTable' => 'priority',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('tasks', 'tasks_sf_guard_user_id_sf_guard_user_id', array(
             'name' => 'tasks_sf_guard_user_id_sf_guard_user_id',
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->addIndex('tasks', 'tasks_priority_id', array(
             'fields' => 
             array(
              0 => 'priority_id',
             ),
             ));
        $this->addIndex('tasks', 'tasks_sf_guard_user_id', array(
             'fields' => 
             array(
              0 => 'sf_guard_user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tasks', 'tasks_priority_id_priority_id');
        $this->dropForeignKey('tasks', 'tasks_sf_guard_user_id_sf_guard_user_id');
        $this->removeIndex('tasks', 'tasks_priority_id', array(
             'fields' => 
             array(
              0 => 'priority_id',
             ),
             ));
        $this->removeIndex('tasks', 'tasks_sf_guard_user_id', array(
             'fields' => 
             array(
              0 => 'sf_guard_user_id',
             ),
             ));
    }
}