<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version25 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeIndex('artist_has_song', 'fk_artist_has_song_artist', array(
             'fields' => 
             array(
              0 => 'artist_id',
             ),
             ));
        $this->removeIndex('artist_has_song', 'fk_artist_has_song_song', array(
             'fields' => 
             array(
              0 => 'song_id',
             ),
             ));
    }

    public function down()
    {
        $this->addIndex('artist_has_song', 'fk_artist_has_song_artist', array(
             'fields' => 
             array(
              0 => 'artist_id',
             ),
             ));
        $this->addIndex('artist_has_song', 'fk_artist_has_song_song', array(
             'fields' => 
             array(
              0 => 'song_id',
             ),
             ));
    }
}