<?php

/**
 * TasksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TasksTable extends PluginTasksTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TasksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tasks');
    }
}