<?php

/**
 * BasePriority
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Users
 * 
 * @method string              getName()  Returns the current record's "name" value
 * @method Doctrine_Collection getUsers() Returns the current record's "Users" collection
 * @method Priority            setName()  Sets the current record's "name" value
 * @method Priority            setUsers() Sets the current record's "Users" collection
 * 
 * @package    Blues
 * @subpackage model
 * @author     Włodzimierz Gajda
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePriority extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('priority');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tasks as Users', array(
             'local' => 'id',
             'foreign' => 'priority_id'));
    }
}